var searchData=
[
  ['magnetic_20helicity_0',['magnetic helicity',['../md_tests_2demo4_2MagneticHelicity__Cart_2README.html',1,'Cartesian finite-volume magnetic helicity'],['../md_doc_2magnetic__helicity.html',1,'Finite-volume magnetic helicity']]],
  ['magnetic_20topology_20and_20qsl_20products_1',['Magnetic Topology and QSL Products',['../md_doc_2magnetic__topology__qsl.html',1,'']]],
  ['magnetic_20topology_20qsl_20regression_2',['Magnetic Topology/QSL Regression',['../md_tests_2mhd_2magnetic__topology__qsl_2README.html',1,'']]],
  ['magnetofriction_3',['Time-dependent magnetofriction',['../md_tests_2demo4_2Data__Driven_2TimeDependentMagnetofriction_2README.html',1,'']]],
  ['magnetofrictional_20relaxation_4',['Data-Driven Magnetofrictional Relaxation',['../md_tests_2demo4_2Data__Driven_2MagnetofrictionalRelaxation_2README.html',1,'']]],
  ['map_5',['UAWSoM equation and implementation map',['../md_doc_2uawsom__equation__map.html',1,'']]],
  ['meetings_6',['Meetings',['../md_doc_2meetings.html',1,'']]],
  ['mesh_20refinement_7',['Adaptive Mesh Refinement',['../md_doc_2amrstructure.html',1,'']]],
  ['meshkov_202d_20test_20problem_8',['Richtmeyer Meshkov 2D test problem',['../md_tests_2hd_2Richtmyer__Meshkov_2Richtmeyer__Meshkov.html',1,'']]],
  ['methods_9',['Numerical methods',['../md_doc_2methods.html',1,'']]],
  ['mhd_10',['mhd',['../md_tests_2demo4_2Data__Driven_2DataDriven_2README.html',1,'B-only data-driven MHD'],['../md_doc_2cakforce.html',1,'CAK radiation force module for HD/MHD'],['../md_tests_2demo4_2Data__Driven_2DataConstrained_2README.html',1,'Data-Driven Data-Constrained MHD'],['../md_doc_2particle.html',1,'Test particle module for HD/MHD']]],
  ['mhd_20rhd_11',['Rotating frame for HD/MHD/RHD',['../md_doc_2rotatingframe.html',1,'']]],
  ['minimal_20tt_20mod_5fusr_20t_20tt_20hook_20for_20topology_20qsl_20namelist_20tasks_12',['Minimal &lt;tt&gt;mod_usr.t&lt;/tt&gt; Hook for Topology/QSL Namelist Tasks',['../md_doc_2examples_2magnetic__topology_2mod__usr__topology__runner__example.html',1,'']]],
  ['mod_5fusr_20t_20tt_20hook_20for_20topology_20qsl_20namelist_20tasks_13',['Minimal &lt;tt&gt;mod_usr.t&lt;/tt&gt; Hook for Topology/QSL Namelist Tasks',['../md_doc_2examples_2magnetic__topology_2mod__usr__topology__runner__example.html',1,'']]],
  ['module_14',['module',['../md_doc_2advection__reaction__diffusion.html',1,'Advection-reaction-diffusion module'],['../md_doc_2reaction__diffusion.html',1,'Reaction-diffusion module']]],
  ['module_20for_20hd_20mhd_15',['module for hd mhd',['../md_doc_2cakforce.html',1,'CAK radiation force module for HD/MHD'],['../md_doc_2particle.html',1,'Test particle module for HD/MHD']]],
  ['module_20to_20mpi_20amrvac_16',['Adding a physics module to MPI-AMRVAC',['../md_doc_2addmodule.html',1,'']]],
  ['modules_20and_20equations_17',['Physics modules and equations',['../md_doc_2equations.html',1,'']]],
  ['mpi_20amrvac_18',['mpi amrvac',['../md_doc_2addmodule.html',1,'Adding a physics module to MPI-AMRVAC'],['../md_doc_2dust.html',1,'Dust in MPI-AMRVAC'],['../md_doc_2publications.html',1,'Publications related to MPI-AMRVAC'],['../md_doc_2radiative__cooling.html',1,'Radiative cooling in MPI-AMRVAC'],['../md_doc_2smallvalues.html',1,'Small values options in MPI-AMRVAC'],['../md_doc_2thermal__conduction.html',1,'Thermal conduction in MPI-AMRVAC']]],
  ['mpi_20amrvac_203_200_20demo_20simulations_19',['MPI-AMRVAC 3.0 Demo simulations',['../md_doc_2demo-movies.html',1,'']]],
  ['mpi_20amrvac_20and_20its_20documentation_20',['Contributing to MPI-AMRVAC and its documentation',['../md_doc_2contributing.html',1,'']]],
  ['mpi_20amrvac_20data_20file_20format_21',['MPI-AMRVAC data file format',['../md_doc_2fileformat.html',1,'']]],
  ['mpi_20amrvac_20documentation_22',['About the MPI-AMRVAC documentation',['../md_doc_2documentation.html',1,'']]]
];
