var searchData=
[
  ['taylor_20instability_20in_202d_0',['Test Rayleigh-Taylor Instability in 2D',['../md_tests_2hd_2Rayleigh__Taylor__2D_2rayleightaylor2d.html',1,'']]],
  ['test_20list_1',['Test List',['../test.html',1,'']]],
  ['test_20particle_20module_20for_20hd_20mhd_2',['Test particle module for HD/MHD',['../md_doc_2particle.html',1,'']]],
  ['test_20problem_3',['test problem',['../md_tests_2mhd_2alfvenwing__3D_2alfvenwing.html',1,'Alfven wing test problem'],['../md_tests_2hd_2Richtmyer__Meshkov_2Richtmeyer__Meshkov.html',1,'Richtmeyer Meshkov 2D test problem'],['../md_tests_2hd_2Woodward__Collela__2D_2Woodward__Collela__2d.html',1,'Woodward-Collela 2D test problem']]],
  ['test_20problem_3a_202d_20hd_20liska_20wendroff_4',['Implosion test problem: 2D HD Liska-Wendroff',['../md_tests_2hd_2implosion__2D_2implosion.html',1,'']]],
  ['test_20problems_5',['Riemann 2D test problems',['../md_tests_2hd_2Riemann__2D_2Riemann__2D.html',1,'']]],
  ['test_20problems_3a_20isothermal_20hd_20variant_6',['Riemann 2D test problems: isothermal HD variant',['../md_tests_2hd_2Riemann__hdiso__2D_2Riemann__iso__2D.html',1,'']]],
  ['test_20rayleigh_20taylor_20instability_20in_202d_7',['Test Rayleigh-Taylor Instability in 2D',['../md_tests_2hd_2Rayleigh__Taylor__2D_2rayleightaylor2d.html',1,'']]],
  ['tests_8',['UAWSoM one-dimensional regression tests',['../md_tests_2mhd_2UAWSoM__1D_2README.html',1,'']]],
  ['the_20dat_20files_9',['Reading the dat files',['../md_doc_2python__datfiles.html',1,'']]],
  ['the_20mpi_20amrvac_20documentation_10',['About the MPI-AMRVAC documentation',['../md_doc_2documentation.html',1,'']]],
  ['the_20python_20tools_11',['Setting up the python tools',['../md_doc_2python__setup.html',1,'']]],
  ['the_20vac_20preprocessor_12',['The VAC preprocessor',['../md_doc_2vacpp.html',1,'']]],
  ['the_20vtk_20files_13',['Reading the vtk files',['../md_doc_2python__vtkfiles.html',1,'']]],
  ['thermal_20conduction_20demonstration_14',['Oblique Fourier thermal-conduction demonstration',['../md_tests_2demo4_2HyperbolicConduction__Fourier_2README.html',1,'']]],
  ['thermal_20conduction_20in_20mpi_20amrvac_15',['Thermal conduction in MPI-AMRVAC',['../md_doc_2thermal__conduction.html',1,'']]],
  ['time_20dependent_20magnetofriction_16',['Time-dependent magnetofriction',['../md_tests_2demo4_2Data__Driven_2TimeDependentMagnetofriction_2README.html',1,'']]],
  ['time_20discretization_17',['Time Discretization',['../md_doc_2time__discretization.html',1,'']]],
  ['to_20dat_20files_18',['Dump variables to dat files',['../md_doc_2dat__convert.html',1,'']]],
  ['to_20mpi_20amrvac_19',['to mpi amrvac',['../md_doc_2addmodule.html',1,'Adding a physics module to MPI-AMRVAC'],['../md_doc_2publications.html',1,'Publications related to MPI-AMRVAC']]],
  ['to_20mpi_20amrvac_20and_20its_20documentation_20',['Contributing to MPI-AMRVAC and its documentation',['../md_doc_2contributing.html',1,'']]],
  ['tools_21',['Setting up the python tools',['../md_doc_2python__setup.html',1,'']]],
  ['topology_20and_20qsl_20products_22',['Magnetic Topology and QSL Products',['../md_doc_2magnetic__topology__qsl.html',1,'']]],
  ['translational_20symmetry_23',['Using axial and translational symmetry',['../md_doc_2axial.html',1,'']]],
  ['transverse_20conduction_20demonstration_24',['Flare current-sheet transverse-conduction demonstration',['../md_tests_2demo4_2HyperbolicConduction__CSHKP_2README.html',1,'']]],
  ['two_20fluid_20equations_25',['Two fluid equations',['../md_doc_2twofluid.html',1,'']]]
];
